services:
  security_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql
    networks:
      - security_network

  app:
    build: .
    container_name: security_app
    ports:
      - "5173:8080"
    depends_on:
      - security_db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
    networks:
      - security_network

volumes:
  postgres-data:

networks:
  security_network: